# Damn vulnerable GraphQL app in the goats namespace
# https://github.com/dolevf/Damn-Vulnerable-GraphQL-Application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dv-graphql
  namespace: goats
  labels:
    app: dv-graphql
spec:
  selector:
    matchLabels:
      app: dv-graphql
  template:
    metadata:
      labels:
        app: dv-graphql
    spec:
      containers:
        - name: dv-graphql
          image: dolevf/dvga
          ports:
            - name: http
              containerPort: 5013
          env:
            - name: WEB_HOST
              value: "0.0.0.0"
            - name: WEB_PORT
              value: "5013"
---
apiVersion: v1
kind: Service
metadata:
  name: dv-graphql
  namespace: goats
  labels:
    app: dv-graphql
spec:
  ports:
    - protocol: TCP
      port: 5013
      targetPort: 5013
  selector:
    app: dv-graphql
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dv-graphql
  namespace: goats
spec:
  # The <namespace>/<name> of the gateway(s) to use.
  # Allows using a centralized gateway, without requiring control over it.
  gateways:
  - istio-ingress/cluster-ingress-gateway
  # The public domain to reach this service.
  hosts:
  - "dv-graphql.cluster.divergent.codes"
  http:
  - match:
    # Every path for this domain will be routed to the service.
    - uri:
        prefix: /
    route:
    - destination:
        host: dv-graphql
        port:
          number: 5013
