---
- name: Provision virtual machines
  hosts: vm_host_server
  become: true
  roles:
    - kvm
  collections:
    - community.libvirt


- name: Provision K3s nodes
  hosts: k3s_node_vms
  become: true
  roles:
    - k3s_node
  vars:
    deb_architecture: {
      "aarch64": "arm64",
      "x86_64": "amd64"
    }

- name: Configure K3s host
  hosts: vm_host_server
  become: true
  roles:
    - k3s_host
  collections:
    - ansible.posix

- name: Configure K3s cluster
  hosts: localhost
  roles:
    - k3s_cluster
  collections:
    - community.aws
    - community.dns
    - kubernetes.core.kustomize
