apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

bases:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.12/manifests/install.yaml

resources:
- namespace.yaml
- argocd-cm.yaml
- argocd-cmd-params-cm.yaml
- argocd-virtualservice.yaml
