# Remote Helm chart for the base External Secrets Operator.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-helm-chart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.5.9
    helm:
      releaseName: external-secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
---
# Resources for external secrets.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:DivergentCodes/ansible-k3s"
    targetRevision: main
    path: cluster-apps/external-secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: false
