---

- name: "Get the current caller identity information"
  amazon.aws.aws_caller_info:
  register: aws_caller_info
  tags:
    - externalsecrets


- name: "Create AWS IAM policy for external secrets to access k3s SSM parameters"
  community.aws.iam_managed_policy:
    policy_name: "k3s-external-secrets-ssm"
    policy_description: "Used by k3s ExternalSecrets to access SSM parameters"
    policy: |
      {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Effect": "Allow",
                  "Action": "ssm:DescribeParameters",
                  "Resource": "*"
              },
              {
                  "Effect": "Allow",
                  "Action": [
                      "ssm:GetParameters",
                      "ssm:GetParameter",
                      "ssm:GetParametersByPath"
                  ],
                  "Resource": "arn:aws:ssm:us-east-1:{{ aws_caller_info.account }}:parameter/{{ k3s.external_secrets.base_path }}/*"
              }
          ]
      }
    state: present
  tags:
    - externalsecrets
  register: aws_iam_policy


- name: "Create AWS user for ExternalSecrets to access SSM"
  community.aws.iam_user:
    name: "k3s-external-secrets-ssm"
    managed_policies:
      - "{{ aws_iam_policy['policy']['arn'] }}"
    state: present
  tags:
    - externalsecrets


- name: "Fetch access keys for ExternalSecrets user"
  community.aws.iam_access_key_info:
    user_name: "k3s-external-secrets-ssm"
  tags:
    - externalsecrets
  register: aws_iam_user_existing_keys


- name: "Create a new access key for ExternalSecrets"
  community.aws.iam_access_key:
    user_name: "k3s-external-secrets-ssm"
    state: present
  tags:
    - externalsecrets
  register: aws_iam_user_new_key
  when: (aws_iam_user_existing_keys['access_keys'] | length) == 0


- name: "Apply manifest for ExternalSecrets AWS IAM user credentials"
  kubernetes.core.k8s:
    kubeconfig: "{{ lookup('env','HOME') }}/.kube/config"
    template: "../templates/external-secrets-aws-credentials.yaml.j2"
    state: present
  tags:
    - externalsecrets
  register: external_secrets_aws_credentials
  when: (aws_iam_user_existing_keys['access_keys'] | length) == 0

