# https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.Certificate
# https://github.com/jetstack/cert-manager/issues/3848
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-certificate-staging
  namespace: istio-ingress
spec:
  commonName: "cluster.divergent.codes"
  dnsNames:
  - "cluster.divergent.codes"
  - "*.cluster.divergent.codes"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  secretName: wildcard-certificate-staging
