apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-external-secret
  namespace: default
  annotations:
    # Required to exclude the generated secret from ArgoCD sync awareness.
    # https://github.com/argoproj/argo-cd/issues/1373#issuecomment-1083379272
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  # refreshInterval: 1h
  secretStoreRef:
    name: primary-cluster-secret-store
    kind: ClusterSecretStore
  data:
  - secretKey: testvar
    remoteRef:
      # SSM parameter store path
      key: /k3s/testvar
