apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: primary-cluster-secret-store
  namespace: external-secrets
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
      # Define a specific role to limit access to certain secrets
      # role: k3s-external-secrets-role
      auth:
        secretRef:
          accessKeyIDSecretRef:
            namespace: kube-system
            name: aws-ssm-credentials
            key: access-key
          secretAccessKeySecretRef:
            namespace: kube-system
            name: aws-ssm-credentials
            key: secret-access-key
